# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.chainergy.com:
    container_name: orderer.chainergy.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/chainergy.com/orderers/orderer.chainergy.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/chainergy.com/orderers/orderer.chainergy.com/tls/:/var/hyperledger/orderer/tls
        - orderer.chainergy.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.producer.chainergy.com:
    container_name: peer0.producer.chainergy.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.producer.chainergy.com
      - CORE_PEER_ADDRESS=peer0.producer.chainergy.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.producer.chainergy.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.producer.chainergy.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.producer.chainergy.com:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/producer.chainergy.com/peers/peer0.producer.chainergy.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/producer.chainergy.com/peers/peer0.producer.chainergy.com/tls:/etc/hyperledger/fabric/tls
        - ../crypto-config/peerOrganizations/producer.chainergy.com/users:/etc/hyperledger/fabric/users
        - peer0.producer.chainergy.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.producer.chainergy.com:
    container_name: peer1.producer.chainergy.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.producer.chainergy.com
      - CORE_PEER_ADDRESS=peer1.producer.chainergy.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.producer.chainergy.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.producer.chainergy.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.producer.chainergy.com:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/producer.chainergy.com/peers/peer1.producer.chainergy.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/producer.chainergy.com/peers/peer1.producer.chainergy.com/tls:/etc/hyperledger/fabric/tls
        - ../crypto-config/peerOrganizations/producer.chainergy.com/users:/etc/hyperledger/fabric/users
        - peer1.producer.chainergy.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.consumer.chainergy.com:
    container_name: peer0.consumer.chainergy.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.consumer.chainergy.com
      - CORE_PEER_ADDRESS=peer0.consumer.chainergy.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.consumer.chainergy.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consumer.chainergy.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.consumer.chainergy.com:10051
      - CORE_PEER_LOCALMSPID=ConsumerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/consumer.chainergy.com/peers/peer0.consumer.chainergy.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/consumer.chainergy.com/peers/peer0.consumer.chainergy.com/tls:/etc/hyperledger/fabric/tls
        - ../crypto-config/peerOrganizations/consumer.chainergy.com/users:/etc/hyperledger/fabric/users
        - peer0.consumer.chainergy.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.consumer.chainergy.com:
    container_name: peer1.consumer.chainergy.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.consumer.chainergy.com
      - CORE_PEER_ADDRESS=peer1.consumer.chainergy.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.consumer.chainergy.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.consumer.chainergy.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.consumer.chainergy.com:9051
      - CORE_PEER_LOCALMSPID=ConsumerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/consumer.chainergy.com/peers/peer1.consumer.chainergy.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/consumer.chainergy.com/peers/peer1.consumer.chainergy.com/tls:/etc/hyperledger/fabric/tls
        - ../crypto-config/peerOrganizations/consumer.chainergy.com/users:/etc/hyperledger/fabric/users
        - peer1.consumer.chainergy.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.shipper.chainergy.com:
    container_name: peer0.shipper.chainergy.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.shipper.chainergy.com
      - CORE_PEER_ADDRESS=peer0.shipper.chainergy.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.shipper.chainergy.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.shipper.chainergy.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.shipper.chainergy.com:12051
      - CORE_PEER_LOCALMSPID=ShipperMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/shipper.chainergy.com/peers/peer0.shipper.chainergy.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/shipper.chainergy.com/peers/peer0.shipper.chainergy.com/tls:/etc/hyperledger/fabric/tls
        - ../crypto-config/peerOrganizations/shipper.chainergy.com/users:/etc/hyperledger/fabric/users
        - peer0.shipper.chainergy.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.shipper.chainergy.com:
    container_name: peer1.shipper.chainergy.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.shipper.chainergy.com
      - CORE_PEER_ADDRESS=peer1.shipper.chainergy.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.shipper.chainergy.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.shipper.chainergy.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.shipper.chainergy.com:11051
      - CORE_PEER_LOCALMSPID=ShipperMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/shipper.chainergy.com/peers/peer1.shipper.chainergy.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/shipper.chainergy.com/peers/peer1.shipper.chainergy.com/tls:/etc/hyperledger/fabric/tls
        - ../crypto-config/peerOrganizations/shipper.chainergy.com/users:/etc/hyperledger/fabric/users
        - peer1.shipper.chainergy.com:/var/hyperledger/production
    ports:
      - 12051:12051

  peer0.transporter.chainergy.com:
    container_name: peer0.transporter.chainergy.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.transporter.chainergy.com
      - CORE_PEER_ADDRESS=peer0.transporter.chainergy.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.transporter.chainergy.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.transporter.chainergy.com:14051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.transporter.chainergy.com:13051
      - CORE_PEER_LOCALMSPID=TransporterMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/transporter.chainergy.com/peers/peer0.transporter.chainergy.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/transporter.chainergy.com/peers/peer0.transporter.chainergy.com/tls:/etc/hyperledger/fabric/tls
        - ../crypto-config/peerOrganizations/transporter.chainergy.com/users:/etc/hyperledger/fabric/users
        - peer0.transporter.chainergy.com:/var/hyperledger/production
    ports:
      - 13051:13051

  peer1.transporter.chainergy.com:
    container_name: peer1.transporter.chainergy.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.transporter.chainergy.com
      - CORE_PEER_ADDRESS=peer1.transporter.chainergy.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer1.transporter.chainergy.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.transporter.chainergy.com:14051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.transporter.chainergy.com:13051
      - CORE_PEER_LOCALMSPID=TransporterMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/transporter.chainergy.com/peers/peer1.transporter.chainergy.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/transporter.chainergy.com/peers/peer1.transporter.chainergy.com/tls:/etc/hyperledger/fabric/tls
        - ../crypto-config/peerOrganizations/transporter.chainergy.com/users:/etc/hyperledger/fabric/users
        - peer1.transporter.chainergy.com:/var/hyperledger/production

    ports:
      - 14051:14051